FROM confluentinc/cp-kafka-connect:latest

ENV CONNECT_BOOTSTRAP_SERVERS 52.78.122.88:9092
ENV CONNECT_CONFIG_STORAGE_TOPIC my-connect-config
ENV CONNECT_OFFSET_STORAGE_TOPIC my-connect-offsets
ENV CONNECT_STATUS_STORAGE_TOPIC my-connect-status
ENV CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR 1
ENV CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR 1

COPY connect-hdfs-source.properties /etc/kafka-connect/

VOLUME /etc/kafka-connect

EXPOSE 8083

CMD ["/usr/bin/connect-standalone", "/etc/kafka/connect-standalone.properties", "/etc/kafka/connect-hdfs-source.properties"]